/**
 * @0xinsider/sdk - official TypeScript SDK for the 0xinsider API.
 *
 * Analytics for Polymarket sports and esports markets: wallet grades, large
 * trades, profitable-wallet flows, market intel/candles, the live SSE feed, and
 * webhooks. Drift-tested
 * against the public OpenAPI contract (`web/public/api/v1/openapi.json`).
 *
 * @example
 * import { OxinsiderApiClient, paginate, streamFeed, verifySignature } from "@0xinsider/sdk";
 *
 * const client = new OxinsiderApiClient({ apiKey: process.env.OXINSIDER_API_KEY });
 * const board = await client.listLeaderboard({ strategy: "swing_trader", limit: 100 });
 */

// Client + core request/response types
export {
  API_CLIENT_OPERATIONS,
  BATCH_TRADER_EXPANSIONS,
  DEFAULT_BASE_URL,
  IDEMPOTENT_WRITE_OPERATIONS,
  READ_ONLY_POST_OPERATIONS,
  retryEligibility,
  DEFAULT_MAX_RETRIES,
  DEFAULT_TIMEOUT_MS,
  SANDBOX_BASE_URL,
  assertTrustedBaseUrl,
  resolveApiUrl,
  composeSignals,
  GRADES,
  LEADERBOARD_STRATEGIES,
  OxinsiderApiClient,
  interpolatePath,
  isApiNotModifiedResponse,
  isListEnvelope,
} from "./client.js";
export type {
  ApiClientMethod,
  ApiClientOperation,
  ApiClientOptions,
  ApiClientResponse,
  ApiEnvelope,
  ApiListEnvelope,
  ApiNotModifiedResponse,
  ApiOperationId,
  ApiQueryValue,
  ApiRequestOptions,
  AuthMode,
  BatchGetTradersOptions,
  BatchTraderExpand,
  CategorySkillStatus,
  CategorySkillStatusCounts,
  ClientMeta,
  ConvenienceOptions,
  EnvelopeOperationId,
  ExploreMarketsParams,
  Grade,
  IdempotentWriteOperationId,
  InsiderRadarListParams,
  LargePositionsListParams,
  ListOperationId,
  ListParams,
  OperationEnvelope,
  OperationItem,
  OperationMeta,
  OperationRequestOptions,
  OperationResult,
  PositionsListParams,
  RetryEligibility,
  SharpMoneyFlowsParams,
  PickQualifyingExpert,
  SportsEdgeSignalsParams,
  SportsEdgeObservationBoardUnavailableScope,
  SportsEdgeObservationBoardUpcomingStatus,
  SportsEdgeObservationCohort,
  SportsEdgeObservationDirectionalStatus,
  SportsEdgeObservationOutcomeIndex,
  SportsEdgeObservationProviderSource,
  SportsEdgeObservationSport,
  SportsEdgeObservationTopGrade,
  SportsEdgeObservationsParams,
  SportsEdgeObservationsResponse,
  TennisTour,
  WhaleTradeHistoryParams,
  LeaderboardListParams,
  LeaderboardStrategy,
  TrendingWalletsParams,
  WhaleTradeListParams,
} from "./client.js";

// Error hierarchy
export {
  API_ERROR_CODES,
  API_ERROR_REASONS,
  AccountLockedError,
  BadRequestError,
  CursorExpiredError,
  ForbiddenError,
  IdempotencyInProgressError,
  InternalServerError,
  InvalidApiKeyError,
  InvalidResponseError,
  NotFoundError,
  OxinsiderApiError,
  PickNotReleasedError,
  RateLimitUnavailableError,
  RequestTimeoutError,
  ServerTimeoutError,
  RateLimitedError,
  ReadModelWarmingError,
  DatabaseUnavailableError,
  RequestAccountingUnavailableError,
  SandboxApiKeyError,
  ApiKeyInQueryError,
  SubscriptionRequiredError,
  TraderNotTrackedError,
  UnknownEndpointError,
  UnknownQueryParameterError,
  WebhookDeliveryInProgressError,
  errorFromResponse,
  extractApiErrorBody,
} from "./errors.js";
export type {
  ApiErrorCode,
  ApiErrorMeta,
  ApiErrorReason,
} from "./errors.js";

// Pagination
export {
  CURSOR_HISTORY_LIMIT,
  PaginationError,
  collect,
  paginate,
  paginatePages,
  paginationResumePoint,
} from "./pagination.js";
export type {
  OperationPaginateOptions,
  PaginateOptions,
  PaginationErrorReason,
  PaginationProgress,
  PaginationResumePoint,
  PaginationStop,
} from "./pagination.js";

// Retry-After parsing and bounded waits, shared by REST and SSE (#16249)
export {
  MAX_TIMER_DELAY_MS,
  RETRY_AFTER_CEILING_MS,
  parseRetryAfter,
} from "./retry.js";

// SSE stream
export {
  DEFAULT_MAX_HANDLER_RETRIES,
  DEFAULT_MAX_STREAM_FRAME_BYTES,
  DEFAULT_MAX_STREAM_RECONNECTS,
  DEFAULT_MAX_STREAM_RETRY_AFTER_MS,
  StreamHandlerFailedError,
  StreamProtocolError,
  StreamReconnectsExhaustedError,
  StreamRetryDeferredError,
  consumeStream,
  consumeStreamCheckpointed,
  decodeStreamFrame,
  isEventStreamMediaType,
  parseSseFrame,
  streamFeed,
  streamFeedResilient,
} from "./stream.js";
export type {
  CheckpointedStreamHandlers,
  CheckpointedStreamOptions,
  FeedEnvelope,
  ParsedSseFrame,
  ResilientStreamOptions,
  ResyncMarker,
  StreamCheckpoint,
  StreamCheckpointReason,
  StreamEvent,
  StreamFilters,
  StreamHandlerFailure,
  StreamHandlerStage,
  StreamOptions,
  StreamProtocolErrorReason,
} from "./stream.js";

// Webhooks
export {
  SIGNATURE_HEADER,
  SIGNATURE_TOLERANCE_SECONDS,
  TIMESTAMP_HEADER,
  WEBHOOK_EVENT_TYPES,
  computeSignature,
  parseWebhookEvent,
  verifySignature,
} from "./webhooks.js";
export type {
  InsiderRadarFlagRaisedData,
  InsiderRadarFlagRaisedEvent,
  LargePositionsUpdatedData,
  LargePositionsUpdatedEvent,
  SmartMoneyFlowDetectedData,
  SmartMoneyFlowDetectedEvent,
  VerifySignatureInput,
  WalletGradeChangedData,
  WalletGradeChangedEvent,
  WebhookEvent,
  WebhookEventEnvelope,
  WhaleTradesInsertedData,
  WhaleTradesInsertedEvent,
  WhaleTraderSyncedData,
  WhaleTraderSyncedEvent,
} from "./webhooks.js";

// Which OpenAPI document this release was generated from (scripts/generate.mjs).
// Compare OPENAPI_SHA256 with the SHA-256 of the live document to see whether a
// release is behind the API.
export {
  APP_COMMIT,
  APP_REPOSITORY,
  APP_SPEC_PATH,
  OPENAPI_SHA256,
  OPENAPI_SOURCE,
  OPENAPI_VERSION,
  OPERATION_COUNT,
} from "./provenance.js";

// Generated contract types (scripts/generate-sdk-types.mjs, #14278). Every
// schema the public OpenAPI document declares, plus the per-operation maps
// (`OperationPath`, `OperationQuery`, `OperationBody`, `OperationData`,
// `OperationResponse`) the client's `call`, `list` and every convenience
// method are typed by (#16136). Regenerate rather than edit:
// `node scripts/generate-sdk-types.mjs`.
export type {
  AgentRegistration,
  ApiDiscovery,
  ApiError,
  BatchMarketIntelItem,
  BatchRateLimitMeta,
  BatchResponseMeta,
  BatchTraderItem,
  Candle,
  ContentSearchResult,
  CounterpartyAnalysis,
  CounterpartyExecution,
  CounterpartyMakerPage,
  CounterpartyMatchBreakdown,
  CounterpartyParticipant,
  CreateWebhookRequest,
  EventReplayEvent,
  EventReplayFreshness,
  EventReplayMeta,
  EventReplaySource,
  ExploreEntry,
  ExploreFacetValue,
  ExploreFacets,
  ExploreGroup,
  ExploreMarket,
  ExploreStandalone,
  ExportCompleteness,
  ExportCounts,
  ExportSourceRange,
  ExportVolumeReconciliation,
  LargeExportPolicy,
  LargePosition,
  LeaderboardEntry,
  MarketCandles,
  MarketIntel,
  MarketSearchResult,
  MarketSnapshot,
  MarketSnapshotFreshness,
  MarketSnapshotTopOfBook,
  MarketSnapshotTrust,
  McpJsonRpcError,
  OutcomeCandles,
  PickHolder,
  PickOfTheDay,
  PickOfTheDayArchive,
  PickOfTheDayArchiveDay,
  PickOfTheDayArchiveEntry,
  PickOfTheDayCommitmentPayload,
  PickOfTheDayHitRate,
  PickOfTheDayLedger,
  PickOfTheDayLedgerEntry,
  PickOfTheDayLedgerOpenedEntry,
  PickOfTheDayLedgerSealedEntry,
  PickOfTheDayLedgerUncommittedEntry,
  PickOfTheDayUncommittedPayload,
  PickSportsContext,
  PickSportsTeam,
  PickTrust,
  PlatformCapabilities,
  PlatformCapabilityStatus,
  Platforms,
  Position,
  PositionTimelineEvent,
  PotdEntryAuthorization,
  ProofPendingPickSlot,
  RadarFlag,
  ReportPayload,
  ReportReconciliation,
  ReportSnapshot,
  ReportSourceRange,
  ResponseMeta,
  ScheduledPickSlot,
  ScoreCell,
  ScoreFormat,
  SmartMoneyFlowMarket,
  SnapshotCompleteness,
  SnapshotState,
  SportsEdgeFunnelReport,
  SportsEdgeObservation,
  SportsEdgeObservationTerminalReason,
  SportsEdgeSignal,
  SportsEdgeSignalCategorySkill,
  SportsEdgeSportFunnelReport,
  Trader,
  TraderCategoryRecord,
  TraderCategoryRecords,
  TraderContext,
  TraderEsportsGameRecord,
  TraderExportJob,
  TraderExportSnapshot,
  TraderPnl,
  TraderTrust,
  TrendingWallet,
  TrustCompleteness,
  TrustFreshness,
  TrustMetadata,
  TrustReconciliation,
  TrustSource,
  UpdateWebhookRequest,
  Usage,
  VerifyWebhookRequest,
  WebhookDelivery,
  WebhookEndpoint,
  WebhookEventDescriptor,
  WebhookRetryPolicy,
  WebhookStatus,
  WebhookVerification,
  WhaleTrade,
  WhaleTradeDetail,
  WhaleTradeHistoryMeta,
  OperationBody,
  OperationData,
  OperationPath,
  OperationQuery,
  OperationResponse,
} from "./schema.js";
