// GENERATED by scripts/generate.mjs. Do not edit.
//
// Which OpenAPI document this release was generated from. OPENAPI_SHA256 is
// the SHA-256 of the document bytes as fetched; APP_COMMIT is the
// 0xinsider/0xinsider commit that last changed web/public/api/v1/openapi.json
// when it could be resolved, else null. Compare OPENAPI_SHA256 with the live
// document to see whether a release is behind the API.

export const OPENAPI_SOURCE = "https://0xinsider.com/api/v1/openapi.json";
export const OPENAPI_SHA256 = "b95ad079d77f9eb1c99722023a3af8fbe46d5c8ac7b983ee67269b8f814eeaad";
export const OPENAPI_VERSION = "1.0.0";
export const OPERATION_COUNT = 67;
export const APP_REPOSITORY = "0xinsider/0xinsider";
export const APP_SPEC_PATH = "web/public/api/v1/openapi.json";
export const APP_COMMIT: string | null = "bd3b0959bddc664b0e82c1e4a7ddfdbe13121ec0";
