// GENERATED by scripts/generate.mjs. Do not edit.
//
// Which OpenAPI document this release was generated from. OPENAPI_SHA256 is
// the SHA-256 of the document bytes as fetched; APP_COMMIT is the
// 0xinsider/0xinsider commit that last changed web/public/api/v1/openapi.json
// when it could be resolved, else null. Compare OPENAPI_SHA256 with the live
// document to see whether a release is behind the API.

export const OPENAPI_SOURCE = "0xinsider/0xinsider:web/public/api/v1/openapi.json";
export const OPENAPI_SHA256 = "c6427f7e37e72014a7a9c1b53b4447137ecddc1f74bbe35ec4653fd2f8bd902f";
export const OPENAPI_VERSION = "1.0.0";
export const OPERATION_COUNT = 88;
export const APP_REPOSITORY = "0xinsider/0xinsider";
export const APP_SPEC_PATH = "web/public/api/v1/openapi.json";
export const APP_COMMIT: string | null = "e0e77bbf198862553e626ed93e21dcef73df3b64";
